# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for Gemini MCP Server - Local Version

FROM node:lts-alpine AS builder

# Install build dependencies
RUN apk add --no-cache python3 make g++

WORKDIR /app

# Copy dependency definitions
COPY package.json package-lock.json tsconfig.json ./
# Copy source code
COPY src ./src

# Install dependencies and build
RUN npm ci --ignore-scripts && \
    npm run build

# Production image
FROM node:lts-alpine
WORKDIR /app

# Copy built app
COPY --from=builder /app/dist ./dist
COPY package.json package-lock.json ./

# Install only production dependencies
RUN npm install --production --ignore-scripts

# Set env and entrypoint
ENV NODE_ENV=production
ENTRYPOINT ["node", "dist/server.js"]
